### ISSUE TITLE
Fix Python 3.12 NumPy Dependancy Installation

### ISSUE THREAD

**Issue by nikolamilojica** [nikolamilojica/illuminate#155]
- [x] make sure that bug hasn't been already submitted by checking [issues](https://github.com/nikolamilojica/illuminate/issues) page
- [x] a detailed description of the bug or problem you are having
- [ ] project dependencies
- [ ] Illuminate and operating system versions
- [ ] minimal example if possible, usually `Observer` or `Adapter` classes from project files
- [x] logs with `--verbosity DEBUG` if possible

___
### Description

The removal of `ImpImporter` from the `pkgutil `module in Python 3.12 has caused compatibility issues with the installation of NumPy version 1.24.4. This deprecation disrupts the installation process, as the `ImpImporter` is no longer available, leading to import errors and preventing successful setup of NumPy.

___
### Dependencies

___
### Versions

___
### Minimal Example

___
### Other Notes

___
### Logs

```
Collecting illuminated==0.3.3
  Using cached illuminated-0.3.3-py3-none-any.whl.metadata (1.3 kB)
Collecting SQLAlchemy<2.0.0,>=1.4.42 (from SQLAlchemy[asyncio]<2.0.0,>=1.4.42->illuminated==0.3.3)
  Using cached SQLAlchemy-1.4.52-cp312-cp312-win_amd64.whl.metadata (10 kB)
Collecting aiofile<4.0.0,>=3.8.1 (from illuminated==0.3.3)
  Using cached aiofile-3.8.8-py3-none-any.whl.metadata (15 kB)
Collecting aioinflux<0.10.0,>=0.9.0 (from illuminated==0.3.3)
  Using cached aioinflux-0.9.0-py3-none-any.whl.metadata (3.8 kB)
Collecting alembic<2.0.0,>=1.7.7 (from illuminated==0.3.3)
  Using cached alembic-1.13.1-py3-none-any.whl.metadata (7.4 kB)
Collecting asyncmy<0.3.0,>=0.2.5 (from illuminated==0.3.3)
  Using cached asyncmy-0.2.9.tar.gz (63 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting asyncpg<0.27.0,>=0.26.0 (from illuminated==0.3.3)
  Using cached asyncpg-0.26.0.tar.gz (809 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting click<9.0.0,>=8.1.2 (from illuminated==0.3.3)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting loguru<0.7.0,>=0.6.0 (from illuminated==0.3.3)
  Using cached loguru-0.6.0-py3-none-any.whl.metadata (21 kB)
Collecting numpy==1.24.4 (from illuminated==0.3.3)
  Using cached numpy-1.24.4.tar.gz (10.9 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [33 lines of output]
  Traceback (most recent call last):
    File "C:\Home\projects\diego\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Home\projects\diego\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Home\projects\diego\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
      backend = _build_backend()
                ^^^^^^^^^^^^^^^^
    File "C:\Home\projects\diego\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
      obj = import_module(mod_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\nikol\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 995, in exec_module
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "C:\Users\nikol\AppData\Local\Temp\pip-build-env-z3bojsna\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
      import setuptools.version
    File "C:\Users\nikol\AppData\Local\Temp\pip-build-env-z3bojsna\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
      import pkg_resources
    File "C:\Users\nikol\AppData\Local\Temp\pip-build-env-z3bojsna\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
      register_finder(pkgutil.ImpImporter, find_on_path)
                      ^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by nikolamilojica** [comment]
Fix is the part of issue https://github.com/nikolamilojica/illuminate/issues/178.
